### ISSUE TITLE
Should `use_package()` remove details set by `use_dev_package()`?

### ISSUE THREAD

**Issue by malcolmbarrett** [r-lib/usethis#1037]
`use_dev_package()` sets a minimum version number and the location of the remote repository. 

E.g., a dev version of ggplot2 produces

```r
# remotes::install_github("tidyverse/ggplot2")
use_dev_package("ggplot2")
```

```yaml
Imports: 
    ggplot2 (>= 3.2.1.9000)
Remotes:  
    tidyverse/ggplot2
```

To me, `use_package()`, by virtue of its contrast with `use_dev_package()`, implies a CRAN package. But if I use `use_package()` after, nothing changes.

```r
# install.packages("ggplot2")
use_package("ggplot2")
```

```yaml
Imports: 
    ggplot2 (>= 3.2.1.9000)
Remotes:  
    tidyverse/ggplot2
```

And using a new min version (as you might after a new CRAN release that has features you depended on from the dev version) only changes that part, assuming the new version is higher than the dev version. It does not modify `Remotes`.

```r
use_package("ggplot2", min_version = TRUE)
```

```yaml
Imports: 
    ggplot2 (>= 3.3.0)
Remotes:  
    tidyverse/ggplot2
```

In principle, this code still works, but it seems like `use_package()` should investigate this more. e.g., if there is an existing dev package, ask `ui_yeah()` if you want to a) upgrade the min version and b) remove remotes. I had expected it to change something, but it didn't. It also seems that to be a reasonable default workflow after depending on a remote dev package.
