### ISSUE TITLE
Fix use_pkgdown_travis() issues related to Tracis-CI dpl v2

### ISSUE THREAD

**Issue by GegznaV** [r-lib/usethis#1092]
It seems that Tracis-CI went to dpl v2 lately. This causes issues in deploying **pkgdown** websites with  `usethis::use_pkgdown_travis()`. E.g., dpl v2 does not use the argument `skip_cleanup` anymore (see [here](https://github.com/travis-ci/dpl#cleaning-up-the-git-working-directory) and warning in figure below), but `use_pkgdown_travis()` still sets this parameter:

https://github.com/r-lib/usethis/blob/b2e894eb6d1d7f3312a783db3bb03a7cc309ba61/R/pkgdown.R#L69

This is a print screen of Travis-CI warnings and messages on settings in `.travis.yml` file:
![image](https://user-images.githubusercontent.com/12725868/78533062-f6852a00-77f0-11ea-9383-19ef3dde1b8f.png)

So as I understand, the deployment code in `.tavis.yml` should look something like this:
```yaml
before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
```

There are other messages that suggest explicitly stating what OS and its distribution should be used and writing the language (i.e., `r`) in lower case but I'm not sure if these are related to **usethis**: 
```yaml
language: r
cache: packages
os: linux
dist: xenial
```
