### ISSUE TITLE
Feature request: Package specific bullets in use_release_issue()

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/usethis#1183]
Having the options to add package-specific steps to the check-list for packages that have more non-traditional workflows.

A release_issue.yml file could be used with a structure like

```yml
before_prepare:
  - "run `vdiffr::manage_cases()`"
  - "run final lint"
  - "Get okay from all maintainers"
after_prepare:
  - "Send out department wide email"
```
