### ISSUE TITLE
Make Ubuntu versions that use_github_actions() functions output more consistent (16.04 vs 20.04)

### ISSUE THREAD

**Issue by Robinlovelace** [r-lib/usethis#1260]
Running `usethis::use_tidy_github_actions()` with the latest dev version of the package outputs this:

Reproducible example:

```r
usethis::use_github_action_check_full()
file.edit(".github/workflows/R-CMD-check.yaml") # open the file
```

Relevant part of the output:

```
jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: '3.6'}
          - {os: ubuntu-16.04,   r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest", http-user-agent: "R/4.0.0 (ubuntu-16.04) R (4.0.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions" }
          - {os: ubuntu-16.04,   r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}
          - {os: ubuntu-16.04,   r: 'oldrel',  rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}
          - {os: ubuntu-16.04,   r: '3.5',     rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}
          - {os: ubuntu-16.04,   r: '3.4',     rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}
          - {os: ubuntu-16.04,   r: '3.3',     rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}
```

I would expect the Ubuntu versions to be updated to the latest stable release. This will make more check pass I think, especially for spatial package. 

Furthermore, updating the Ubuntu version would make the package more internally consistent. Adding the 'standard' check yields a version of Ubuntu that was published 4 years later, which is much more useful for developers and less likely to need custom .yml files to add new repos (e.g. as links to this issue show https://github.com/r-lib/actions/issues/163 )  :

```r
usethis::use_github_action_check_standard()
file.edit(".github/workflows/R-CMD-check.yaml") # open the file
```

Relevant part of the output:

```
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          - {os: ubuntu-20.04, r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
```

There may be advantages of using such an base OS for tidyverse tests but thought it worth flagging as I think it could save a lot of time for the many users who use the tidyverse versions.

A summary of the Ubuntu version resulting from different `use_github_actions()` functions I've tried:

- `use_github_action_check_full()`: 16.04
- `use_github_action_check_standard()`: 20.04
- `use_tidy_github_actions()`: 16.04

There are various possible solutions to make the OS outputs more consistent, including allowing the user to choose the Ubuntu version with a consistent default (I would suggest 20.04 Long Term release for future proofing) and a simpler solution, updating all functions so they consistently use the latest Long Term Support version of Ubuntu by default. There may be other good solutions and maybe good reasons for the inconsistency highlighted above that I'm not aware of, but confident that making the Ubuntu versions outputed by these CI commands consistent and more up-to-date will save lots of time for `usethis` users.
