### ISSUE TITLE
travis yaml should include addons if usethis/gert is dependency

### ISSUE THREAD

**Issue by mrcaseb** [r-lib/usethis#1317]
As this is a CI problem I can't provide a reprex, sorry.

Currently the `use_travis()` function creates a yaml file with the following code 

```yaml
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
``` 

The checks on Travis failed for my package because I have got `usethis` as a dependency which has `gert` as a dependency which requires libgit2 to be installed on the system (please see the following screenshot of the travis log).

<img width="938" alt="image" src="https://user-images.githubusercontent.com/38586519/102895184-8bee4a00-4464-11eb-90a0-b4eee0920ab3.png">

I found this solution https://github.com/r-lib/gert/issues/23#issuecomment-619511969 in the `gert` repo which is working fine for me. 

So I would suggest `use_travis()` creates the following yaml if `usethis` or `gert` are dependencies:

```yaml
# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
addons:
  apt:
    packages:
      - libgit2-dev
```
