### ISSUE TITLE
`pandoc-citeproc` needed for bookdown rendering

### ISSUE THREAD

**Issue by chendaniely** [r-lib/usethis#1431]
`pandoc-citeproc` is still needed to render references in bookdown (and possibly other places). However, `brew` no longer has `pandoc-citeproc` in the repo (https://formulae.brew.sh/formula/pandoc-citeproc).

The newer release of `usethis` reflects on the changes from `brew` by removing `pandoc-citeproc` from the installation steps (https://raw.githubusercontent.com/r-lib/actions/master/examples/bookdown.yaml), but the book will fail to build because bookdown will need to use citeproc to build.

These are the error messages from my own GH action builds:

Just making an update after 6 months
https://github.com/chendaniely/ds4biomed/runs/2376439679?check_suite_focus=true

```
Error: pandoc-citeproc has been disabled because it is deprecated upstream!
Error: Process completed with exit code 1.
```

Using updated `bookdown.yaml` file will pass the Install pandoc step, but will fail in the build site step
https://github.com/chendaniely/ds4biomed/runs/2376490402?check_suite_focus=true

```
Warning:  Deprecated: pandoc-citeproc filter. Use --citeproc instead.
Error running filter pandoc-citeproc:
Could not find executable pandoc-citeproc
Error: Error: pandoc document conversion failed with error 83
Execution halted
Error: Process completed with exit code 1.
```

Moved the `runs-on` from `mac-latest` to `ubuntu-latest- and add in `pandoc-citeproc` and `libcurl4-openssl-dev` along with some `renv` changes to get rid of the `rJava` dependency (`rJava` is not relevant to this issue)

https://github.com/chendaniely/ds4biomed/actions/runs/761956577

This is the `bookdown.yaml` file that worked for me

```yaml
on:
  push:
    branches:
      - main
      - master

name: bookdown

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc pandoc-citeproc
        run: |
          sudo apt-get update -y
          sudo apt-get install -y pandoc pandoc-citeproc

      - name: Install system libraries
        run: |
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Cache bookdown results
        uses: actions/cache@v2
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Build site
        run: Rscript -e 'bookdown::render_book("index.Rmd", quiet = TRUE, new_session = TRUE)'

      - name: Install npm
        uses: actions/setup-node@v1

      - name: Deploy to Netlify
        # NETLIFY_AUTH_TOKEN and NETLIFY_SITE_ID added in the repo's secrets
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install netlify-cli -g
          netlify deploy --prod --dir _book
```

Is this a PR I should make into `r-lib`? for the yaml template? I'm not totally sure why `citeproc` was removed from `brew`, but is this potentially an issue in `bookdown`?
I also understand that the mac image was picked because it might make installing the R packages faster, so I'm not entirely sure what the correct "fix" would be?
