### ISSUE TITLE
Feature request: GH Action commit 

### ISSUE THREAD

**Issue by ldecicco-USGS** [r-lib/usethis#2031]
I have no idea if this is possible or not. My organization does not allow version tags to be used in GH actions. They are concerned about security, since the tagged version can be altered without us knowing. So for example, when I use `usethis::use_github_action_check_standard()`, I need to change things from:

```
   steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
etc...
```
to
```
  steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08

      - uses: r-lib/actions/setup-pandoc@6012817847b5f064d0882d67a7b5e2ca6639afb2

      - uses: r-lib/actions/setup-r@15cf1013badbaf6d25f100593ad5d7d75e65d64b
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@96b1dc658a45175f93ed5f33fda2b2cebbb12ee8
etc...
```
Would it be possible to offer an option to add an argument (or separate function or something) to fetch the most recent commit tag that is associated with the "v2" tag?
