### ISSUE TITLE
Tweaks for tidy-travis.yml

### ISSUE THREAD

**Issue by hadley** [r-lib/usethis#455]
```yaml
language: R
sudo: false
cache: packages

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
  - r: oldrel
  - r: 3.3
  - r: 3.2
  - r: 3.1
```

This ensures ensures that the most recent versions of R build first, and that code coverage is only run with R-release (and provides easy hooks for doing other stuff with that version, i.e. building pkgdown sites)
