### ISSUE TITLE
Stale Bot

### ISSUE THREAD

**Issue by muschellij2** [r-lib/usethis#598]
Issue open from #593 to add `use_*bot` functions, such as Stale bot: https://github.com/apps/stale.

This issue is to open the discussion of bots, not necessarily enable the `use_stale` rejected PR from below.  Overall, this discussion should at least cover:

1.  Should bots be in `usethis` for `use_*` functions
2. How should `.github` be incorporated into the creation.  Such as, I'm not sure if `use_github` should create `.github` folder and put in `.Rbuildignore`.
3. Should template go in `inst/templates` like others?

---

Example of `inst/templates/stale.yml`:
```yml
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
```

Here is an example of the docs for `R/stale.R`.
```r
#' Add Stale Bot
#'
#' `use_stale()` Adds [GitHub Stale Bot](https://github.com/apps/stale) to
#' add Stale bot to your repository
#'
#' @inheritParams use_template
#' @export
use_stale <- function(open = interactive()) {
  check_uses_github()
  if (!dir.exists(".github")) {
    dir.create(".github", showWarnings = FALSE)
    usethis::use_build_ignore(".github")
  }
  new <- use_template(
    "stale.yml",
    ".github/stale.yml",
    ignore = TRUE,
    open = open
  )
  if (open) {
    utils::browseURL("https://github.com/apps/stale")
  }
  if (!new) return(invisible(FALSE))

  invisible(TRUE)
}
```
