### ISSUE TITLE
incoherence between use_pkgdown_travis and pkgdown docs

### ISSUE THREAD

**Issue by cderv** [r-lib/usethis#747]
In pkgdown, the doc says to configure `.travis.yml` like this
https://github.com/r-lib/pkgdown/blob/master/R/deploy-site.R#L13
```yaml
before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
```
however, `use_pkgdown_travis` advice this 
https://github.com/r-lib/usethis/blob/815debaca2b80036d3eea1366195087da1cab0f6/R/pkgdown.R#L58-L62

So, should it be `before_cache` or `before_deploy` ? 
From 781ea9eb6a031555e75a2a5dd4e2d9372e3c03d3, it seems pkgdown docs require an update. 🤔 

Should I open an improvement about documentation in pkgdown repo ?
