### ISSUE TITLE
Quiet option for use_coverage()

### ISSUE THREAD

**Issue by lionel-** [r-lib/usethis#8]
It should:

- ask the user for a target percentage for the project (say 70% by default)
- set the patch target to zero
- set both thresholds to 100%

```yaml
comment: false

coverage:
  status:
    project:
      default:
        target: 70
        threshold: 100
    patch:
      default:
        target: 0
        threshold: 100
```

**Comment by jennybc** [comment]
I also fiddled with this today. Context: you want to keep getting codecov reports on commits and PRs but you don't want Codecov to ever fail, i.e. be the reason for ❌ on the build.

Most useful docs: https://docs.codecov.io/docs/commit-status

This variant sets the target percentage to "whatever it is in the base" and tolerates coverage decrease of 10%:

```yml
comment: false
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
    patch:
      default:
        target: auto
        threshold: 10%
```

This variant suppresses all reporting directly on the gh commit or PR but the report is still available over at codecov.io:

```yml
coverage:
  status:
    project: off
    patch: off
```
